export const data = JSON.parse("{\"key\":\"v-2174f106\",\"path\":\"/zh/guide/JUnit5/191701.html\",\"title\":\"JUnit5介绍\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"JUnit5介绍\",\"icon\":\"circle-info\",\"order\":191701,\"description\":\"JUnit5介绍 本章要点 JUnit5是什么; JUnit5组成; 测试用例主要用到哪部分; ### Junit5 特点 1. JUnit 5 是面向 Java 8 及更高版本的开源测试框架，可以完全替换或兼容JUnit 4。 新的版本肯定要兼容旧的版本以及旧版本的技术，只是新版本增加了自己特有的一些特性，或者是有些使用方式上「比如：导包，对应包的位...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/guide/JUnit5/191701.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"教程\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"JUnit5介绍\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"JUnit5介绍 本章要点 JUnit5是什么; JUnit5组成; 测试用例主要用到哪部分; ### Junit5 特点 1. JUnit 5 是面向 Java 8 及更高版本的开源测试框架，可以完全替换或兼容JUnit 4。 新的版本肯定要兼容旧的版本以及旧版本的技术，只是新版本增加了自己特有的一些特性，或者是有些使用方式上「比如：导包，对应包的位...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"nikita\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"JUnit5介绍\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"nikita\\\",\\\"url\\\":\\\"https://github.com/SoulGai\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"JUnit5介绍\",\"slug\":\"junit5介绍\",\"link\":\"#junit5介绍\",\"children\":[{\"level\":3,\"title\":\"本章要点\",\"slug\":\"本章要点\",\"link\":\"#本章要点\",\"children\":[]},{\"level\":3,\"title\":\"Junit5 特点\",\"slug\":\"junit5-特点\",\"link\":\"#junit5-特点\",\"children\":[]},{\"level\":3,\"title\":\"JUnit5组成\",\"slug\":\"junit5组成\",\"link\":\"#junit5组成\",\"children\":[{\"level\":5,\"title\":\"Junit Platform\",\"slug\":\"junit-platform\",\"link\":\"#junit-platform\",\"children\":[]},{\"level\":5,\"title\":\"Junit Jupiter\",\"slug\":\"junit-jupiter\",\"link\":\"#junit-jupiter\",\"children\":[]},{\"level\":5,\"title\":\"Junit Vintage\",\"slug\":\"junit-vintage\",\"link\":\"#junit-vintage\",\"children\":[]}]},{\"level\":3,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[{\"level\":6,\"title\":\"JUnit5组成\",\"slug\":\"junit5组成-1\",\"link\":\"#junit5组成-1\",\"children\":[]},{\"level\":6,\"title\":\"测试用例编写用到哪个模块\",\"slug\":\"测试用例编写用到哪个模块\",\"link\":\"#测试用例编写用到哪个模块\",\"children\":[]}]}]}],\"readingTime\":{\"minutes\":3.59,\"words\":1076},\"filePathRelative\":\"zh/guide/JUnit5/191701.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
