export const data = JSON.parse("{\"key\":\"v-0a503a7f\",\"path\":\"/zh/guide/interview/1080813.html\",\"title\":\"adb面试题\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"adb面试题\",\"icon\":\"circle-info\",\"order\":1080813,\"description\":\"什么是 ADB？ ::: details Answer ADB 是 Android 调试桥的缩写，是 Android 开发工具集的一部分。它是一个命令行工具，用于在计算机和 Android 设备之间建立连接，并提供多种功能，如文件传输、应用程序安装、调试、性能分析等。 ::: adb 安装路径 adb 版本号 如何连接到 Android 设备或模拟器？...\"},\"headers\":[{\"level\":2,\"title\":\"什么是 ADB？\",\"slug\":\"什么是-adb\",\"link\":\"#什么是-adb\",\"children\":[]},{\"level\":2,\"title\":\"adb 安装路径\",\"slug\":\"adb-安装路径\",\"link\":\"#adb-安装路径\",\"children\":[]},{\"level\":2,\"title\":\"adb 版本号\",\"slug\":\"adb-版本号\",\"link\":\"#adb-版本号\",\"children\":[]},{\"level\":2,\"title\":\"如何连接到 Android 设备或模拟器？\",\"slug\":\"如何连接到-android-设备或模拟器\",\"link\":\"#如何连接到-android-设备或模拟器\",\"children\":[]},{\"level\":2,\"title\":\"设备连接状态\",\"slug\":\"设备连接状态\",\"link\":\"#设备连接状态\",\"children\":[]},{\"level\":2,\"title\":\"如何安装应用程序到 Android 设备上？\",\"slug\":\"如何安装应用程序到-android-设备上\",\"link\":\"#如何安装应用程序到-android-设备上\",\"children\":[]},{\"level\":2,\"title\":\"如何卸载应用程序？\",\"slug\":\"如何卸载应用程序\",\"link\":\"#如何卸载应用程序\",\"children\":[]},{\"level\":2,\"title\":\"如何查看日志输出？\",\"slug\":\"如何查看日志输出\",\"link\":\"#如何查看日志输出\",\"children\":[]},{\"level\":2,\"title\":\"列出已安装的应⽤程序包\",\"slug\":\"列出已安装的应用程序包\",\"link\":\"#列出已安装的应用程序包\",\"children\":[]},{\"level\":2,\"title\":\"清除应⽤程序的⽤户数据和缓存\",\"slug\":\"清除应用程序的用户数据和缓存\",\"link\":\"#清除应用程序的用户数据和缓存\",\"children\":[]},{\"level\":2,\"title\":\"查看软件包的安装程序来源\",\"slug\":\"查看软件包的安装程序来源\",\"link\":\"#查看软件包的安装程序来源\",\"children\":[]},{\"level\":2,\"title\":\"应用程序启动\",\"slug\":\"应用程序启动\",\"link\":\"#应用程序启动\",\"children\":[]},{\"level\":2,\"title\":\"获取应用程序启动页面的Activity\",\"slug\":\"获取应用程序启动页面的activity\",\"link\":\"#获取应用程序启动页面的activity\",\"children\":[]},{\"level\":2,\"title\":\"如何强制停止应用程序？\",\"slug\":\"如何强制停止应用程序\",\"link\":\"#如何强制停止应用程序\",\"children\":[]},{\"level\":2,\"title\":\"如何模拟来电或发送短信？\",\"slug\":\"如何模拟来电或发送短信\",\"link\":\"#如何模拟来电或发送短信\",\"children\":[]},{\"level\":2,\"title\":\"如何复制文件到设备？\",\"slug\":\"如何复制文件到设备\",\"link\":\"#如何复制文件到设备\",\"children\":[]},{\"level\":2,\"title\":\"如何从设备复制文件到计算机？\",\"slug\":\"如何从设备复制文件到计算机\",\"link\":\"#如何从设备复制文件到计算机\",\"children\":[]},{\"level\":2,\"title\":\"压⼒测试monkey\",\"slug\":\"压力测试monkey\",\"link\":\"#压力测试monkey\",\"children\":[]},{\"level\":2,\"title\":\"ADB 通信原理\",\"slug\":\"adb-通信原理\",\"link\":\"#adb-通信原理\",\"children\":[]}],\"readingTime\":{\"minutes\":3.78,\"words\":1133},\"filePathRelative\":\"zh/guide/interview/1080813.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
