export const data = JSON.parse("{\"key\":\"v-28f3c60a\",\"path\":\"/zh/guide/interface/1072505.html\",\"title\":\"Postman前后置脚本\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Postman前后置脚本\",\"icon\":\"circle-info\",\"order\":1072505,\"description\":\"本章要点 1. Postman前后置脚本编写 2. 后置脚本断言编写 学习目标 1. 熟练掌握Postman中如何编写前后置脚本 2. 熟练掌握JS语句进行断言 思考 Question 想要编写脚本在Postman请求发送前或请求响应后执行，如何进行操作？ 在Postman中，前置脚本（Pre-request Script）和后置脚本（Tests）是用...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/guide/interface/1072505.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"教程\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Postman前后置脚本\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"本章要点 1. Postman前后置脚本编写 2. 后置脚本断言编写 学习目标 1. 熟练掌握Postman中如何编写前后置脚本 2. 熟练掌握JS语句进行断言 思考 Question 想要编写脚本在Postman请求发送前或请求响应后执行，如何进行操作？ 在Postman中，前置脚本（Pre-request Script）和后置脚本（Tests）是用...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"盖盖\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Postman前后置脚本\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"盖盖\\\",\\\"url\\\":\\\"https://github.com/Nikita-GDev\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"本章要点\",\"slug\":\"本章要点\",\"link\":\"#本章要点\",\"children\":[]},{\"level\":2,\"title\":\"学习目标\",\"slug\":\"学习目标\",\"link\":\"#学习目标\",\"children\":[]},{\"level\":2,\"title\":\"思考\",\"slug\":\"思考\",\"link\":\"#思考\",\"children\":[]},{\"level\":2,\"title\":\"前置脚本（Pre-request Script）\",\"slug\":\"前置脚本-pre-request-script\",\"link\":\"#前置脚本-pre-request-script\",\"children\":[{\"level\":3,\"title\":\"脚本设置\",\"slug\":\"脚本设置\",\"link\":\"#脚本设置\",\"children\":[]}]},{\"level\":2,\"title\":\"后置脚本（Tests）\",\"slug\":\"后置脚本-tests\",\"link\":\"#后置脚本-tests\",\"children\":[{\"level\":3,\"title\":\"响应状态码断言\",\"slug\":\"响应状态码断言\",\"link\":\"#响应状态码断言\",\"children\":[]},{\"level\":3,\"title\":\"响应时间断言\",\"slug\":\"响应时间断言\",\"link\":\"#响应时间断言\",\"children\":[]},{\"level\":3,\"title\":\"响应体断言\",\"slug\":\"响应体断言\",\"link\":\"#响应体断言\",\"children\":[]},{\"level\":3,\"title\":\"随机请求参数获取\",\"slug\":\"随机请求参数获取\",\"link\":\"#随机请求参数获取\",\"children\":[]}]},{\"level\":2,\"title\":\"debug调试\",\"slug\":\"debug调试\",\"link\":\"#debug调试\",\"children\":[]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[]},{\"level\":2,\"title\":\"学习反馈\",\"slug\":\"学习反馈\",\"link\":\"#学习反馈\",\"children\":[]}],\"readingTime\":{\"minutes\":4.54,\"words\":1362},\"filePathRelative\":\"zh/guide/interface/1072505.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
