export const data = JSON.parse("{\"key\":\"v-2e2477c4\",\"path\":\"/zh/guide/interview-01/1080801.html\",\"title\":\"Web自动化测试面试题\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Web自动化测试面试题\",\"icon\":\"circle-info\",\"description\":\"介绍一下你对自动化测试的理解和重要性 自动化测试是一种使用脚本和工具来执行测试任务的方法，以代替手动执行测试。通过编写自动化测试脚本，可以模拟用户在应用程序中的各种操作和交互，从而自动化地验证软件的功能、性能和稳定性。以下是我对自动化测试的理解和重要性的详细介绍： 理解 自动化脚本 自动化测试依赖于编写脚本或代码，以模拟用户行为并执行测试用例。 自动化...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/guide/interview-01/1080801.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"教程\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Web自动化测试面试题\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"介绍一下你对自动化测试的理解和重要性 自动化测试是一种使用脚本和工具来执行测试任务的方法，以代替手动执行测试。通过编写自动化测试脚本，可以模拟用户在应用程序中的各种操作和交互，从而自动化地验证软件的功能、性能和稳定性。以下是我对自动化测试的理解和重要性的详细介绍： 理解 自动化脚本 自动化测试依赖于编写脚本或代码，以模拟用户行为并执行测试用例。 自动化...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"盖盖\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Web自动化测试面试题\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"盖盖\\\",\\\"url\\\":\\\"https://github.com/Nikita-GDev\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"介绍一下你对自动化测试的理解和重要性\",\"slug\":\"介绍一下你对自动化测试的理解和重要性\",\"link\":\"#介绍一下你对自动化测试的理解和重要性\",\"children\":[{\"level\":3,\"title\":\"理解\",\"slug\":\"理解\",\"link\":\"#理解\",\"children\":[{\"level\":4,\"title\":\"自动化脚本\",\"slug\":\"自动化脚本\",\"link\":\"#自动化脚本\",\"children\":[]},{\"level\":4,\"title\":\"自动化工具\",\"slug\":\"自动化工具\",\"link\":\"#自动化工具\",\"children\":[]},{\"level\":4,\"title\":\"自动化流程\",\"slug\":\"自动化流程\",\"link\":\"#自动化流程\",\"children\":[]}]}]},{\"level\":2,\"title\":\"自动化常见问题\",\"slug\":\"自动化常见问题\",\"link\":\"#自动化常见问题\",\"children\":[{\"level\":4,\"title\":\"场景1: 点击页面的某个元素，会跳转到新的页面。\",\"slug\":\"场景1-点击页面的某个元素-会跳转到新的页面。\",\"link\":\"#场景1-点击页面的某个元素-会跳转到新的页面。\",\"children\":[{\"level\":5,\"title\":\"解决方案\",\"slug\":\"解决方案\",\"link\":\"#解决方案\",\"children\":[]}]},{\"level\":3,\"title\":\"解决方案：\",\"slug\":\"解决方案-1\",\"link\":\"#解决方案-1\",\"children\":[{\"level\":4,\"title\":\"原因：\",\"slug\":\"原因\",\"link\":\"#原因\",\"children\":[]},{\"level\":4,\"title\":\"解决方案：\",\"slug\":\"解决方案-2\",\"link\":\"#解决方案-2\",\"children\":[]},{\"level\":4,\"title\":\"解决方案：\",\"slug\":\"解决方案-3\",\"link\":\"#解决方案-3\",\"children\":[]}]}]},{\"level\":2,\"title\":\"显式等待与隐式等待区别\",\"slug\":\"显式等待与隐式等待区别\",\"link\":\"#显式等待与隐式等待区别\",\"children\":[]},{\"level\":2,\"title\":\"Selenium原理\",\"slug\":\"selenium原理\",\"link\":\"#selenium原理\",\"children\":[]}],\"readingTime\":{\"minutes\":4.92,\"words\":1475},\"filePathRelative\":\"zh/guide/interview-01/1080801.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
