export const data = JSON.parse("{\"key\":\"v-303a9b16\",\"path\":\"/zh/guide/performance/1071805-.html\",\"title\":\"JMeter运行配置\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"JMeter运行配置\",\"icon\":\"circle-info\",\"order\":1071805,\"description\":\"本章要点 1. 运行模块介绍 2. 选项模块介绍 学习目标 1. 运行、选项模块使用。 思考 Question JMeter脚本编写完成后如何运行？对应的界面都是英文显示，不友好，如何把JMeter界面设置为中文？ 运行模块 本篇文章介绍运行下拉菜单，先不介绍远程相关的知识。在后续使用到时再详细介绍。 启动 启动运行当前的测试计划。 当前测试计划有等待...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/guide/performance/1071805-.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"教程\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"JMeter运行配置\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"本章要点 1. 运行模块介绍 2. 选项模块介绍 学习目标 1. 运行、选项模块使用。 思考 Question JMeter脚本编写完成后如何运行？对应的界面都是英文显示，不友好，如何把JMeter界面设置为中文？ 运行模块 本篇文章介绍运行下拉菜单，先不介绍远程相关的知识。在后续使用到时再详细介绍。 启动 启动运行当前的测试计划。 当前测试计划有等待...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"盖盖\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"JMeter运行配置\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"盖盖\\\",\\\"url\\\":\\\"https://github.com/Nikita-GDev\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"本章要点\",\"slug\":\"本章要点\",\"link\":\"#本章要点\",\"children\":[]},{\"level\":2,\"title\":\"学习目标\",\"slug\":\"学习目标\",\"link\":\"#学习目标\",\"children\":[]},{\"level\":2,\"title\":\"思考\",\"slug\":\"思考\",\"link\":\"#思考\",\"children\":[]},{\"level\":2,\"title\":\"运行模块\",\"slug\":\"运行模块\",\"link\":\"#运行模块\",\"children\":[{\"level\":3,\"title\":\"启动\",\"slug\":\"启动\",\"link\":\"#启动\",\"children\":[]},{\"level\":3,\"title\":\"不停顿开始\",\"slug\":\"不停顿开始\",\"link\":\"#不停顿开始\",\"children\":[]},{\"level\":3,\"title\":\"清除\",\"slug\":\"清除\",\"link\":\"#清除\",\"children\":[]},{\"level\":3,\"title\":\"清除全部\",\"slug\":\"清除全部\",\"link\":\"#清除全部\",\"children\":[]}]},{\"level\":2,\"title\":\"选项模块\",\"slug\":\"选项模块\",\"link\":\"#选项模块\",\"children\":[{\"level\":3,\"title\":\"选择语言\",\"slug\":\"选择语言\",\"link\":\"#选择语言\",\"children\":[]},{\"level\":3,\"title\":\"日志查看\",\"slug\":\"日志查看\",\"link\":\"#日志查看\",\"children\":[]},{\"level\":3,\"title\":\"全部折叠\",\"slug\":\"全部折叠\",\"link\":\"#全部折叠\",\"children\":[]},{\"level\":3,\"title\":\"全部展开\",\"slug\":\"全部展开\",\"link\":\"#全部展开\",\"children\":[]}]},{\"level\":2,\"title\":\"JMeter界面功能总结\",\"slug\":\"jmeter界面功能总结\",\"link\":\"#jmeter界面功能总结\",\"children\":[]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[]}],\"readingTime\":{\"minutes\":2.8,\"words\":841},\"filePathRelative\":\"zh/guide/performance/1071805-.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
