export const data = JSON.parse("{\"key\":\"v-03d3881a\",\"path\":\"/zh/guide/performance/1071809-.html\",\"title\":\"代理服务器录制原理\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"代理服务器录制原理\",\"icon\":\"circle-info\",\"order\":1071809,\"description\":\"本章要点 1. 录制压测脚本原理 1. 录制的请求流程 学习目标 1. 掌握录制的原理 思考 Question 代理服务器录制原理 本篇文章主要了解代理服务器的原理，无论是JMeter自带的代理服务器还是第三方代理录制服务器。它是通过怎样的方式把客户端的操作请求生成对应的压测脚本。 简单画了一下原理图，根据原理图来给大家讲解一下对应的流程： 请求 当客...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/guide/performance/1071809-.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"教程\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"代理服务器录制原理\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"本章要点 1. 录制压测脚本原理 1. 录制的请求流程 学习目标 1. 掌握录制的原理 思考 Question 代理服务器录制原理 本篇文章主要了解代理服务器的原理，无论是JMeter自带的代理服务器还是第三方代理录制服务器。它是通过怎样的方式把客户端的操作请求生成对应的压测脚本。 简单画了一下原理图，根据原理图来给大家讲解一下对应的流程： 请求 当客...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"盖盖\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"代理服务器录制原理\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"盖盖\\\",\\\"url\\\":\\\"https://github.com/Nikita-GDev\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"本章要点\",\"slug\":\"本章要点\",\"link\":\"#本章要点\",\"children\":[]},{\"level\":2,\"title\":\"学习目标\",\"slug\":\"学习目标\",\"link\":\"#学习目标\",\"children\":[]},{\"level\":2,\"title\":\"思考\",\"slug\":\"思考\",\"link\":\"#思考\",\"children\":[]},{\"level\":2,\"title\":\"代理服务器录制原理\",\"slug\":\"代理服务器录制原理\",\"link\":\"#代理服务器录制原理\",\"children\":[{\"level\":3,\"title\":\"请求\",\"slug\":\"请求\",\"link\":\"#请求\",\"children\":[]},{\"level\":3,\"title\":\"场景\",\"slug\":\"场景\",\"link\":\"#场景\",\"children\":[{\"level\":4,\"title\":\"无代理服务器请求流程\",\"slug\":\"无代理服务器请求流程\",\"link\":\"#无代理服务器请求流程\",\"children\":[]},{\"level\":4,\"title\":\"代理服务器请求流程\",\"slug\":\"代理服务器请求流程\",\"link\":\"#代理服务器请求流程\",\"children\":[]}]},{\"level\":3,\"title\":\"代理服务器录制流程\",\"slug\":\"代理服务器录制流程\",\"link\":\"#代理服务器录制流程\",\"children\":[{\"level\":4,\"title\":\"CA证书作用\",\"slug\":\"ca证书作用\",\"link\":\"#ca证书作用\",\"children\":[]}]}]},{\"level\":2,\"title\":\"代理服务器介绍\",\"slug\":\"代理服务器介绍\",\"link\":\"#代理服务器介绍\",\"children\":[]},{\"level\":2,\"title\":\"录制优点\",\"slug\":\"录制优点\",\"link\":\"#录制优点\",\"children\":[]},{\"level\":2,\"title\":\"总结【补充】\",\"slug\":\"总结【补充】\",\"link\":\"#总结【补充】\",\"children\":[]}],\"readingTime\":{\"minutes\":3.57,\"words\":1071},\"filePathRelative\":\"zh/guide/performance/1071809-.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
