export const data = JSON.parse("{\"key\":\"v-3e86290e\",\"path\":\"/zh/guide/springboot3/1081801.html\",\"title\":\"POST请求\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"POST请求\",\"icon\":\"circle-info\",\"order\":1081801,\"description\":\"本章要点 1. 学习目标 1. 思考 Question 如何使用SpringBoot开发POST请求的Web程序？ POST请求如何携带参数？在代码中如何使用？ 一.POST参数传递方式 在 HTTP 请求中，POST 请求通常通过 请求体（Request Body） 传递参数，而不是像 GET 请求那样通过路径参数或查询参数。在 POST 请求中，数...\"},\"headers\":[{\"level\":2,\"title\":\"本章要点\",\"slug\":\"本章要点\",\"link\":\"#本章要点\",\"children\":[]},{\"level\":2,\"title\":\"学习目标\",\"slug\":\"学习目标\",\"link\":\"#学习目标\",\"children\":[]},{\"level\":2,\"title\":\"思考\",\"slug\":\"思考\",\"link\":\"#思考\",\"children\":[]},{\"level\":2,\"title\":\"一.POST参数传递方式\",\"slug\":\"一-post参数传递方式\",\"link\":\"#一-post参数传递方式\",\"children\":[{\"level\":3,\"title\":\"1.JSON 数据\",\"slug\":\"_1-json-数据\",\"link\":\"#_1-json-数据\",\"children\":[]},{\"level\":3,\"title\":\"2.表单数据\",\"slug\":\"_2-表单数据\",\"link\":\"#_2-表单数据\",\"children\":[]},{\"level\":3,\"title\":\"3.Multipart 表单数据\",\"slug\":\"_3-multipart-表单数据\",\"link\":\"#_3-multipart-表单数据\",\"children\":[]},{\"level\":3,\"title\":\"4.其他数据格式\",\"slug\":\"_4-其他数据格式\",\"link\":\"#_4-其他数据格式\",\"children\":[]}]},{\"level\":2,\"title\":\"二.Json格式的请求创建\",\"slug\":\"二-json格式的请求创建\",\"link\":\"#二-json格式的请求创建\",\"children\":[{\"level\":3,\"title\":\"用户实体类创建\",\"slug\":\"用户实体类创建\",\"link\":\"#用户实体类创建\",\"children\":[]},{\"level\":3,\"title\":\"用户注册接口创建\",\"slug\":\"用户注册接口创建\",\"link\":\"#用户注册接口创建\",\"children\":[]},{\"level\":3,\"title\":\"验证\",\"slug\":\"验证\",\"link\":\"#验证\",\"children\":[]}]},{\"level\":2,\"title\":\"三.表单数据\",\"slug\":\"三-表单数据\",\"link\":\"#三-表单数据\",\"children\":[]},{\"level\":2,\"title\":\"四.Multipart 表单数据\",\"slug\":\"四-multipart-表单数据\",\"link\":\"#四-multipart-表单数据\",\"children\":[]},{\"level\":2,\"title\":\"五.XML格式数据\",\"slug\":\"五-xml格式数据\",\"link\":\"#五-xml格式数据\",\"children\":[{\"level\":3,\"title\":\"1.pom文件导入对应依赖\",\"slug\":\"_1-pom文件导入对应依赖\",\"link\":\"#_1-pom文件导入对应依赖\",\"children\":[]},{\"level\":3,\"title\":\"2.创建一个 Java 类来表示 XML 数据的结构\",\"slug\":\"_2-创建一个-java-类来表示-xml-数据的结构\",\"link\":\"#_2-创建一个-java-类来表示-xml-数据的结构\",\"children\":[{\"level\":4,\"title\":\"@XmlElement\",\"slug\":\"xmlelement\",\"link\":\"#xmlelement\",\"children\":[{\"level\":5,\"title\":\"在 Java 类的字段上\",\"slug\":\"在-java-类的字段上\",\"link\":\"#在-java-类的字段上\",\"children\":[]},{\"level\":5,\"title\":\"在 Java 类的 getter 方法上\",\"slug\":\"在-java-类的-getter-方法上\",\"link\":\"#在-java-类的-getter-方法上\",\"children\":[]}]},{\"level\":4,\"title\":\"实体类代码\",\"slug\":\"实体类代码\",\"link\":\"#实体类代码\",\"children\":[]}]},{\"level\":3,\"title\":\"3.Controller 中处理 XML POST 请求\",\"slug\":\"_3-controller-中处理-xml-post-请求\",\"link\":\"#_3-controller-中处理-xml-post-请求\",\"children\":[]},{\"level\":3,\"title\":\"验证\",\"slug\":\"验证-1\",\"link\":\"#验证-1\",\"children\":[]}]}],\"readingTime\":{\"minutes\":6.5,\"words\":1950},\"filePathRelative\":\"zh/guide/springboot3/1081801.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
