export const data = JSON.parse("{\"key\":\"v-44eb5c5e\",\"path\":\"/zh/guide/springboot3/1082103-.html\",\"title\":\"Bean注入\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Bean注入\",\"icon\":\"circle-info\",\"order\":1082103,\"description\":\"本章要点 1. 学习目标 1. 思考 Question Bean注入如何实现？ 如何指定注入组件的名称？ 注入的组件是单实例还是多实例？ 单实例和多实例在什么节点注入到ioc容器中？ @Configuration注解+@Bean方法 在配置类上添加 @Configuration 注解，然后在其中使用 @Bean 注解创建 Bean 对象。 这种方式可以...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/guide/springboot3/1082103-.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"教程\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Bean注入\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"本章要点 1. 学习目标 1. 思考 Question Bean注入如何实现？ 如何指定注入组件的名称？ 注入的组件是单实例还是多实例？ 单实例和多实例在什么节点注入到ioc容器中？ @Configuration注解+@Bean方法 在配置类上添加 @Configuration 注解，然后在其中使用 @Bean 注解创建 Bean 对象。 这种方式可以...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"盖盖\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Bean注入\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"盖盖\\\",\\\"url\\\":\\\"https://github.com/Nikita-GDev\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"本章要点\",\"slug\":\"本章要点\",\"link\":\"#本章要点\",\"children\":[]},{\"level\":2,\"title\":\"学习目标\",\"slug\":\"学习目标\",\"link\":\"#学习目标\",\"children\":[]},{\"level\":2,\"title\":\"思考\",\"slug\":\"思考\",\"link\":\"#思考\",\"children\":[]},{\"level\":2,\"title\":\"@Configuration注解+@Bean方法\",\"slug\":\"configuration注解-bean方法\",\"link\":\"#configuration注解-bean方法\",\"children\":[{\"level\":3,\"title\":\"创建组件\",\"slug\":\"创建组件\",\"link\":\"#创建组件\",\"children\":[]},{\"level\":3,\"title\":\"创建配置类\",\"slug\":\"创建配置类\",\"link\":\"#创建配置类\",\"children\":[]}]},{\"level\":2,\"title\":\"指定组件名\",\"slug\":\"指定组件名\",\"link\":\"#指定组件名\",\"children\":[]},{\"level\":2,\"title\":\"设置组件作用域-@Scope\",\"slug\":\"设置组件作用域-scope\",\"link\":\"#设置组件作用域-scope\",\"children\":[{\"level\":3,\"title\":\"单实例\",\"slug\":\"单实例\",\"link\":\"#单实例\",\"children\":[]},{\"level\":3,\"title\":\"多实例\",\"slug\":\"多实例\",\"link\":\"#多实例\",\"children\":[]}]},{\"level\":2,\"title\":\"组件注入节点\",\"slug\":\"组件注入节点\",\"link\":\"#组件注入节点\",\"children\":[{\"level\":3,\"title\":\"singleton\",\"slug\":\"singleton\",\"link\":\"#singleton\",\"children\":[]},{\"level\":3,\"title\":\"prototype\",\"slug\":\"prototype\",\"link\":\"#prototype\",\"children\":[]}]},{\"level\":2,\"title\":\"Bean组件懒加载\",\"slug\":\"bean组件懒加载\",\"link\":\"#bean组件懒加载\",\"children\":[]}],\"readingTime\":{\"minutes\":3.8,\"words\":1139},\"filePathRelative\":\"zh/guide/springboot3/1082103-.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
